task :default do
  p 'hello'
  ['https://ist.ksc.kwansei.ac.jp/~nishitani/?LectureNotes',
   'linear_algebra.pages.pdf','la.key','projection.mw'].each do |target|
    system "open #{target}"
  end
  system 'new_terminal|jupyter notebook'
end
