require 'colorize'

$attach = '/Users/bob/Sites/new_ist_data/ist_data/cache/attach/NumRecipe'
$nbviewer = 'https://nbviewer.org/github/daddygongon/jupyter_num_calc/blob/main/numerical_calc'

task :default do
  system 'rake -T'
end

desc 'mk link and rsync with dir'
task :mk_link do
  puts "$attach = %s".blue % $attach
  puts "$nbview = %s".yellow % $nbviewer
  if ARGV[1] == nil
    comment = <<~COMMENT
    discomment FileUtils.cp in 'Rakefile'
    and delete comment out after 'hiki open NumRecipe'
    COMMENT
    puts comment.cyan
    exit
  else
    target_files = Dir.glob(ARGV[1])
  end

  target_files.each do |file|
    next if file =~ /Rakefile/
    next if File.extname(file) =~ /\.tex|\.mw|\.bb|\.png|\.org|\.html/
    puts file.green
    basename = File.basename(file)
    target = File.join($attach,basename, verbose: truels)
    FileUtils.cp(file, target)
    if File.extname(file)=='.ipynb'
      print "||{{attach_anchor_string(------, #{basename}) }} ".blue
      print "([[nbviewer|#{$nbviewer}/#{file}]])\n".cyan
    else
      puts "{{attach_anchor(#{basename})}}"
    end
  end
  exit
end

