require 'open3'
require 'colorize'

task :default do
  system 'rake -T'
end
desc 'make problem from ans'
task :split do
  p file = ARGV[1]
  unless file =~ /_ans.ipynb$/
    puts 'wrong file?'.red
    exit
  else
    p splitter = File.join(File.dirname(__FILE__),'bin/pick_works_from_ans.rb')
    system "ruby #{splitter} #{file}"
    puts "check ipynb, cause additional markdown or remaining code parts...".red
    puts "directly remove them or remain them like ...".red
    puts "ruby bin/pick_works_from_ans.rb gitignores/gw2_diff_ans.ipynb -1 '17 23' ''".red
  end
  exit
end
desc 'rsync'
task :rsync do
  src = '/Users/bob/Desktop/Lectures/math_python/jupyter_num_calc/symbolic_math/'
  attach = '/Users/bob/Sites/new_ist_data/ist_data/cache/attach/DoingMathWithPython/'
  ["rsync -v -ptgo --stats *.ipynb #{attach}",
   "ls -lat *.ipynb",
   "ls -lat #{File.join(attach, '*.ipynb')}"].each_with_index do |command, i|
    out, _err, _status = Open3.capture3(command)
    case i
    when 0; print out.green
    when 1; print out.red
    when 2; print out.blue
    end
  end
end

desc 'rsync_gw5_pdf'
task :rsync_gw5_pdf do
  src = '/Users/bob/Desktop/Lectures/math_python/jupyter_num_calc/symbolic_math/'
  attach = '/Users/bob/Sites/new_ist_data/ist_data/cache/attach/DoingMathWithPython/'
  file = 'gw5_center_exams.pdf'
  p command = "cp #{src}/#{file} #{attach}"
  out, _err, _status = Open3.capture3(command)
end

desc 'link' "make link"
task :link do
  Dir.glob("*.ipynb").each do |ipynb|
    puts "([[nbviewer|https://nbviewer.org/github/daddygongon/jupyter_num_calc/blob/main/symbolic_math/#{ipynb}]])"
  end
end
