require 'colorize'

$attach = '/Users/bob/Sites/new_ist_data/ist_data/cache/attach/NumRecipe'
$nbviewer = 'https://nbviewer.org/github/daddygongon/jupyter_num_calc/blob/main/numerical_calc'

task :default do
  system 'rake -T'
end

desc 'mk link and rsync with dir'
task :mk_link do
  puts "$attach = %s".blue % $attach
  puts "$nbview = %s".yellow % $nbviewer
  if ARGV[1] == nil
    comment = <<~COMMENT
    cp target files to hiki and nbviewer directory and make links.
    need ARGV[1] as follows with ''
    './marked_pdfs/d*.pdf', 'pdfs/*.pdf', 'ipynb_txt/d*.ipynb',
    and 'report_ans/r*.ipynb'
    and '*.data, *.pdf or *.ipynb'
    COMMENT
    puts comment.cyan
    exit
  else
    target_files = Dir.glob(ARGV[1])
  end

  target_files.each do |file|
    puts file.green
    basename = File.basename(file)
    target = File.join($attach,basename)
    FileUtils.cp(file, target)
    if File.extname(file)=='.ipynb'
      print "||{{attach_anchor_string(------, #{basename}) }} ".blue
      print "([[nbviewer|#{$nbviewer}/#{file}]])\n".cyan
    else
      puts "{{attach_anchor(#{basename})}}"
    end
  end
  exit
end

