require 'colorize'

$attach = '/Users/bob/Sites/new_ist_data/ist_data/cache/attach/NumRecipe'
$nbviewer = 'https://nbviewer.org/github/daddygongon/jupyter_num_calc/blob/main/numerical_calc'

task :default do
  system 'rake -T'
end

desc 'mk link and rsync with dir'
task :mk_link do
  puts "$attach = %s".blue % $attach
  puts "$nbview = %s".yellow % $nbviewer
  ['./marked_pdfs/d*.pdf', 'pdfs/*.pdf', 'ipynb_text/d*.ipynb',
   'report_ans/r*.ipynb'].each do |dir|
    p dir
    target_files = Dir.glob(dir)

    target_files.each do |file|
      next if File.directory?(file)
      puts file.green
      basename = File.basename(file)
      target = File.join($attach,basename)
      FileUtils.cp(file, target)
      if File.extname(file)=='.ipynb'
        print "||{{attach_anchor_string(------, #{basename}) }} ".blue
        print "([[nbviewer|#{$nbviewer}/#{file}]])\n".cyan
      else
        puts "{{attach_anchor(#{basename})}}"
      end
    end
  end
  exit
end

