$attach = '/Users/bob/Sites/new_ist_data/ist_data/cache/attach/NumRecipe'
puts "$attach = %s" % $attach
$nbviewer = 'https://nbviewer.org/github/daddygongon/jupyter_num_calc/blob/main/numerical_calc'
puts "$nbview = %s" % $nbviewer

task :default do
  system 'rake -T'
end

desc 'mk link and rsync marked_pdfs '
task :mk_link do
  if ARGV[1] == nil
    puts "Need ARGV[1] as follows with ''"
    puts './marked_pdfs/d*.pdf'
    puts '*.data, *.pdf or *.ipynb'
    exit
  else
    target_files = Dir.glob(ARGV[1])
  end
  target_files.each do |file|
    p file
    basename = File.basename(file)
    target = File.join($attach,basename)
    if File.extname(file)=='.ipynb'
      print "||{{attach_anchor_string(------, #{target}) || "
      print "([[#{$nbviewer}/#{file}][nbviewer]])\n"
    else
      puts "{{attach_anchor(#{basename})}}"
    end
    FileUtils.cp(file, target)
  end
  exit
end

